import type { AnalysisResult } from "@/types"

/**
 * Generates and triggers download of an analysis report as an HTML file
 * that can be printed to PDF. This uses browser native print functionality.
 */
export function exportAnalysisReport(result: AnalysisResult) {
  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Candidate Analysis Report - ${result.candidateName}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #0f172a; line-height: 1.6; max-width: 800px; margin: 0 auto; padding: 40px 20px; }
    .header { border-bottom: 3px solid #2563eb; padding-bottom: 20px; margin-bottom: 30px; }
    .header h1 { font-size: 28px; color: #2563eb; margin-bottom: 4px; }
    .header p { color: #64748b; font-size: 14px; }
    .section { margin-bottom: 30px; }
    .section h2 { font-size: 20px; color: #0f172a; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px; margin-bottom: 16px; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; }
    .score-ring { width: 120px; height: 120px; margin: 0 auto 16px; }
    .score-label { text-align: center; }
    .badge { display: inline-block; padding: 4px 12px; border-radius: 100px; font-size: 12px; font-weight: 600; }
    .badge-green { background: #d1fae5; color: #065f46; }
    .badge-red { background: #fee2e2; color: #991b1b; }
    .badge-blue { background: #dbeafe; color: #1e40af; }
    .badge-amber { background: #fef3c7; color: #92400e; }
    .skill-tag { display: inline-block; padding: 2px 10px; border-radius: 6px; font-size: 12px; margin: 2px; border: 1px solid; }
    .tag-match { background: #d1fae5; border-color: #6ee7b7; color: #065f46; }
    .tag-miss { background: #fee2e2; border-color: #fca5a5; color: #991b1b; }
    .tag-extra { background: #dbeafe; border-color: #93c5fd; color: #1e40af; }
    .score-bar { height: 8px; border-radius: 4px; background: #e2e8f0; margin: 8px 0; overflow: hidden; }
    .score-bar-fill { height: 100%; border-radius: 4px; }
    ul { padding-left: 20px; }
    li { margin-bottom: 6px; font-size: 14px; }
    .score-large { font-size: 36px; font-weight: bold; text-align: center; }
    .rec-badge { display: inline-block; padding: 6px 20px; border-radius: 8px; font-size: 16px; font-weight: 700; margin: 0 auto; display: block; text-align: center; }
    @media print { .no-print { display: none; } }
  </style>
</head>
<body>
  <div class="header">
    <h1>Candidate Analysis Report</h1>
    <p>Generated by ResumeScreener AI — ${new Date().toLocaleDateString()}</p>
  </div>

  <div class="section">
    <h2>Candidate Profile</h2>
    <div class="grid">
      <div>
        <p><strong>Name:</strong> ${result.candidateName}</p>
        <p><strong>Email:</strong> ${result.email}</p>
        <p><strong>Phone:</strong> ${result.phone}</p>
      </div>
      <div>
        <p><strong>Education:</strong> ${result.education}</p>
        <p><strong>Experience:</strong> ${result.experienceYears} years</p>
        <p><strong>Previous Roles:</strong> ${result.previousRoles.join(", ")}</p>
      </div>
    </div>
  </div>

  <div class="section">
    <h2>Match Analysis</h2>
    <div style="text-align: center; margin-bottom: 16px;">
      <div class="score-large" style="color: ${result.matchScore >= 80 ? "#10b981" : result.matchScore >= 60 ? "#f59e0b" : "#ef4444"}">${result.matchScore}%</div>
      <p style="color: #64748b; font-size: 14px;">Overall Match Score</p>
    </div>
    <div class="rec-badge" style="background: ${result.recommendation === "Strong Hire" ? "#d1fae5" : result.recommendation === "Hire" ? "#dbeafe" : result.recommendation === "Consider" ? "#fef3c7" : "#fee2e2"}; color: ${result.recommendation === "Strong Hire" ? "#065f46" : result.recommendation === "Hire" ? "#1e40af" : result.recommendation === "Consider" ? "#92400e" : "#991b1b"}">${result.recommendation}</div>
    <div style="margin-top: 16px;">
      <p><strong>Skills Score:</strong> ${result.skillsScore}%</p>
      <div class="score-bar"><div class="score-bar-fill" style="width: ${result.skillsScore}%; background: ${result.skillsScore >= 80 ? "#10b981" : result.skillsScore >= 60 ? "#f59e0b" : "#ef4444"}"></div></div>
      <p><strong>Experience Score:</strong> ${result.experienceScore}%</p>
      <div class="score-bar"><div class="score-bar-fill" style="width: ${result.experienceScore}%; background: ${result.experienceScore >= 80 ? "#10b981" : result.experienceScore >= 60 ? "#f59e0b" : "#ef4444"}"></div></div>
      <p><strong>Education Score:</strong> ${result.educationScore}%</p>
      <div class="score-bar"><div class="score-bar-fill" style="width: ${result.educationScore}%; background: ${result.educationScore >= 80 ? "#10b981" : result.educationScore >= 60 ? "#f59e0b" : "#ef4444"}"></div></div>
      <p><strong>ATS Compatibility:</strong> ${result.atsScore}%</p>
      <p><strong>Resume Quality:</strong> ${result.resumeQualityScore}%</p>
    </div>
  </div>

  <div class="section">
    <h2>Skill Analysis</h2>
    <p><strong>Matched Skills:</strong></p>
    <div style="margin-bottom: 12px;">${result.matchedSkills.map((s) => `<span class="skill-tag tag-match">${s}</span>`).join(" ")}</div>
    <p><strong>Missing Skills:</strong></p>
    <div style="margin-bottom: 12px;">${result.missingSkills.map((s) => `<span class="skill-tag tag-miss">${s}</span>`).join(" ")}</div>
    <p><strong>Additional Skills:</strong></p>
    <div style="margin-bottom: 12px;">${result.additionalSkills.map((s) => `<span class="skill-tag tag-extra">${s}</span>`).join(" ")}</div>
    <p><strong>Programming Languages:</strong> ${result.programmingLanguages.join(", ")}</p>
    <p><strong>Certifications:</strong> ${result.certifications.length > 0 ? result.certifications.join(", ") : "None listed"}</p>
  </div>

  <div class="section">
    <div class="grid">
      <div>
        <h2>Strengths</h2>
        <ul>${result.strengths.map((s) => `<li>${s}</li>`).join("")}</ul>
      </div>
      <div>
        <h2>Areas for Improvement</h2>
        <ul>${result.weaknesses.map((w) => `<li>${w}</li>`).join("")}</ul>
      </div>
    </div>
  </div>

  <div class="section">
    <h2>AI Evaluation Summary</h2>
    <p style="font-style: italic; color: #475569;">${result.summary}</p>
  </div>
</body>
</html>`

  const blob = new Blob([html], { type: "text/html" })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = `candidate-report-${result.candidateName.toLowerCase().replace(/\s+/g, "-")}.html`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
